controller_manager:
  ros__parameters:

    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    effort_controller:
      type: forward_command_controller/ForwardCommandController


effort_controller:
  ros__parameters:

    joints:
      - base_yaw_joint
      - shoulder_joint
      - elbow_joint
      - wrist_pitch_joint
      - wrist_roll_joint
      - gripper_servo_joint

    interface_name: effort